### ISSUE TITLE
Issue with long timelapse inputs

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#13]
For videos 300 frames or less, processing is fine. But above 300 I run into errors.

I am not sure if it is to do with images or if it is something else?

```
python3 gopro2gsv.py \
        --input_directory tests/UKHB/UKHB002v205/ \
        --video_telemetry_format GPMD \
        --output_filepath tests/output/long_gpmd_video_without_nadir/long_gpmd_video_without_nadir.mp4
04-Sep-23 19:43:18 [GoPro2GSV] [INFO] ====================================================
04-Sep-23 19:43:18 [GoPro2GSV] [INFO] =====================GoPro2GSV======================
04-Sep-23 19:43:18 [GoPro2GSV] [INFO] ====================================================
04-Sep-23 19:43:18 [GoPro2GSV] [INFO] Saving log to `/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/tests/output/long_gpmd_video_without_nadir/long_gpmd_video_without_nadir.log`
04-Sep-23 19:43:18 [GoPro2GSV] [INFO] =====================GoPro2GSV======================
04-Sep-23 19:43:51 [GoPro2GSV] [WARNING] Image's exif data missing `GPS:GPSLatitudeRef`
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/shell_helper.py", line 37, in run_command_silently
    output = subprocess.check_output(cmd, encoding='utf-8', **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['exiftool', '-ee', '-G3', '-n', '-X', '-api', 'LargeFileSupport=1', 'tests/UKHB/UKHB002v205/GSAB8631.JPG']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/gopro2gsv.py", line 5, in <module>
    main(*parse_args())
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/__main__.py", line 111, in main
    valid_images, invalid_files = get_files_from_dir(input_dir)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/imagetool.py", line 73, in get_files_from_dir
    metadata = metadata_dict(test_image(str(f)))
                             ^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/shell_helper.py", line 88, in test_image
    exif_data = get_exif_details(path)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/shell_helper.py", line 74, in get_exif_details
```

Test files: https://drive.google.com/drive/folders/1FxBmXUtb5KYq_avENZgGB5eXF3sNGR0Z?usp=drive_link

**Comment by fqrious** [comment]
![image](https://github.com/trek-view/gopro2gsv/assets/29603874/e687a573-4152-4914-94dc-f80db3d303ee)
****

The issue is one of the images wasn't valid and the problem wasn't because it was too long
