### ISSUE TITLE
video inputs broken

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#18]
```
python3 gopro2gsv.py \
	--input_video tests/ski/GS016843.mp4 \
	--output_filepath tests/output/gpmd_video_input_add_nadir.mp4
```

```
05-Sep-23 14:30:45 [GoPro2GSV] [INFO] ====================================================
05-Sep-23 14:30:45 [GoPro2GSV] [INFO] =====================GoPro2GSV======================
05-Sep-23 14:30:45 [GoPro2GSV] [INFO] ====================================================
05-Sep-23 14:30:45 [GoPro2GSV] [INFO] Saving log to `/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/tests/output/gpmd_video_input_add_nadir.log`
05-Sep-23 14:30:45 [GoPro2GSV] [INFO] =====================GoPro2GSV======================
05-Sep-23 14:30:47 [GoPro2GSV] [INFO] Found 5376x2688 video with 188 valid frames at tests/ski/GS016843.mp4
05-Sep-23 14:30:47 [GoPro2GSV] [INFO] Post-processing video #1 of 1
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/gopro2gsv.py", line 5, in <module>
    main(*parse_args())
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/__main__.py", line 196, in main
    gopro2gsv(args, is_photo_mode, logger)
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/__main__.py", line 189, in gopro2gsv
    database.insert_output(args.input_video.absolute(), newpath, log_filepath, streetview_info=streetview_id, is_photo_mode=False)
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/sql_helper.py", line 95, in insert_output
    cursor.execute(f'''
sqlite3.OperationalError: table Video has no column named gpx_file
```

**Comment by himynamesdave** [comment]
To test
https://drive.google.com/file/d/1HR72XL3Jf7JoAo_j_Zi52MRrvFyPFSuZ/view?usp=drive_link

**Comment by fqrious** [comment]
Whenever you run into db error, please remove stale db first before
reporting an issue. Thanks

**Comment by himynamesdave** [comment]
@fqrious i deleted the sqlite.db file and still running into this issue
