### ISSUE TITLE
Add .360 video mode

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#28]
Currently we suppport .mp4 video mode.

GoPro MAX cameras also produce a .360 video format.

For GoPro MAX Unprocessed Video mode (`.360`):

1. takes GoPro .360 video (equirectangular) with GPMF data
2. converts to an equirectangular frames
3. optionally adds a nadir to the resulting video
4. stores output/uploads output/etc

**Comment by himynamesdave** [comment]
@fqrious ask for max2sphere binary (ideally clone it on install as a gitmodule). This is what https://github.com/trek-view/gopro2frames does

**Comment by himynamesdave** [comment]
Getting the following issue. 

Note, I see the `_preprocessing` and `_processed` directories, all with images in.


```shell
python3 gopro2gsv.py \
	--input_video tests/360_file/GS019359.360 \
	--extract_fps 0.5 \
	--keep_extracted_frames \
	--output_filepath tests/output/mode4/test1/GS019359.mp4
```

```
o tests/360_file/GS019359.360 \
        --extract_fps 0.5 \
        --keep_extracted_frames \
        --output_filepath tests/output/mode4/test1/GS019359.mp4
30-Nov-23 08:33:41 [GoPro2GSV] [INFO] ====================================================
30-Nov-23 08:33:41 [GoPro2GSV] [INFO] =====================GoPro2GSV======================
30-Nov-23 08:33:41 [GoPro2GSV] [INFO] ====================================================
30-Nov-23 08:33:41 [GoPro2GSV] [INFO] Saving log to `/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/tests/output/mode4/test1/GS019359.log`
30-Nov-23 08:33:41 [GoPro2GSV] [INFO] =====================GoPro2GSV======================
30-Nov-23 08:33:41 [GoPro2GSV] [INFO] extracting images
Warning: [minor] The ExtractEmbedded option may find more tags in the media data - tests/360_file/GS019359.360
30-Nov-23 08:36:04 [GoPro2GSV] [INFO] Tagging 76 images
30-Nov-23 08:36:05 [GoPro2GSV] [INFO] Processing video #1 of 1
30-Nov-23 08:36:05 [GoPro2GSV] [INFO] generating gpx file for video #1 at tests/output/mode4/test1/GS019359-1.gpx
30-Nov-23 08:36:05 [GoPro2GSV] [INFO] generating video #1 at tests/output/mode4/test1/GS019359-1_DIRTY.mp4
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/shell_helper.py", line 39, in run_command_silently
    output = subprocess.check_output(cmd, encoding='utf-8', **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-r', '5', '-i', 'tests/output/mode4/test1/GS019359.mp4/_processed/%05d.jpg', '-vframes', '76', '-y', 'tests/output/mode4/test1/GS019359-1_DIRTY.mp4']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/gopro2gsv.py", line 5, in <module>
    main(*parse_args())
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/__main__.py", line 217, in main
    gopro2gsv(args, is_photo_mode, logger)
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/__main__.py", line 178, in gopro2gsv
    videos = process_into_videos(valid_images, TIMELAPSE_FRAME_RATE, args.max_output_video_secs, output_filepath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/imagetool.py", line 150, in process_into_videos
    create_video_from_images(frame_glob, mp4_file, frame_cursor, end-frame_cursor, frame_rate=framerate, date=first_image['date'])
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/shell_helper.py", line 150, in create_video_from_images
    run_command_silently(cmd, stderr=subprocess.DEVNULL)
  File "/Users/dgreenwood/Documents/repos/trek-view/gopro2gsv/src/shell_helper.py", line 44, in run_command_silently
    raise RuntimeError(f"Error running command `{cmd_str}`: {error_message}")
RuntimeError: Error running command `'ffmpeg' '-r' '5' '-i' 'tests/output/mode4/test1/GS019359.mp4/_processed/%05d.jpg' '-vframes' '76' '-y' 'tests/output/mode4/test1/GS019359-1_DIRTY.mp4'`: 

```
