### ISSUE TITLE
Issue with missing directories -- validation and retry required

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#58]
```
11-Dec-23 08:31:40 [GoPro2GSV] [INFO] =====================GoPro2GSV======================11-Dec-23 08:31:40 [GoPro2GSV] [INFO] extracting images11-Dec-23 08:33:39 [GoPro2GSV] [INFO] video `GS010059.mp4` split into 739 frames, took 113.631578 secondsWarning: End of processing at large atom (LargeFileSupport not enabled) - /Volumes/tvhdd1A/BACKUP/trekview/panos/projects/ucpa-ski/val-thorens/2022-03-02/95-FRVT-4-GS010059/GS010059.mp4Warning: No writable tags set from /Volumes/tvhdd1A/BACKUP/trekview/panos/projects/ucpa-ski/val-thorens/2022-03-02/95-FRVT-4-GS010059/GS010059.mp411-Dec-23 08:33:40 [GoPro2GSV] [INFO] Tagging 739 imagesTraceback (most recent call last):  File "/Users/dgreenwood/Downloads/gopro2gsv/gopro2gsv.py", line 5, in <module>    main(*parse_args())  File "/Users/dgreenwood/Downloads/gopro2gsv/src/__main__.py", line 221, in main    gopro2gsv(args, is_photo_mode, logger)  File "/Users/dgreenwood/Downloads/gopro2gsv/src/__main__.py", line 182, in gopro2gsv    videos = process_into_videos(valid_images, TIMELAPSE_FRAME_RATE, args.max_output_video_secs, output_filepath)  File "/Users/dgreenwood/Downloads/gopro2gsv/src/imagetool.py", line 115, in process_into_videos    valid_images = write_images_to_dir(images, frame_glob.parent)  File "/Users/dgreenwood/Downloads/gopro2gsv/src/imagetool.py", line 166, in write_images_to_dir    shutil.copyfile(path, newpath)  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/tvhdd1A/BACKUP/trekview/panos/projects/ucpa-ski/val-thorens/2022-03-02/95-FRVT-4-GS010059/processed/95-FRVT-4-GS010059-trek_view_processed_full_nadir/_preprocessing/FRAME-00121.jpg'(gopro2gsv-venv) dgreenwood@Davids-MBP gopro2gsv % python3 gopro2gsv.py --extract_fps 2 --keep_extracted_frames --max_output_video_secs 30 --input_video /Volumes/tvhdd1A/BACKUP/trekview/panos/projects/ucpa-ski/val-thorens/2022-02-28/60-FRVT-2-GS010018/GS010018.mp4 --path_to_nadir stock_nadirs/without_gopro/trek_view_full_nadir.png --size_of_nadir 25 --output_filepath /Volumes/tvhdd1A/BACKUP/trekview/panos/projects/ucpa-ski/val-thorens/2022-02-28/60-FRVT-2-GS010018/processed/60-FRVT-2-GS010018-trek_view_processed_full_nadir
```

**Comment by fqrious** [comment]
While this can be implemented, it makes more sense to fix the drive issue.
